theme: jekyll-theme-cayman
title: Voxel Workshop for PhoneGap Day 2017 NYC
description: This guide will show users how to use MagicaVoxel, export their 3D models, and view it on their phones using WebVR and A-Frame. 